# Starship config for Gruvbox theme

format = """
[](#d79921)\
$os\
$username\
[](bg:#fabd2f fg:#d79921)\
$directory\
[](fg:#fabd2f bg:#427b58)\
$git_branch\
$git_status\
[](fg:#427b58 bg:#282828)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julial\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#282828)\
"""

[os]
style = "bg:#d79921 fg:#282828"
disabled = false

[os.symbols]
Arch = "  "
Linux = " "

[username]
show_always = false
style_user = "bg:#d79921 fg:#282828 bold"
style_root = "bg:#d79921 fg:#282828 bold"
format = '[$user ]($style)'

[directory]
style = "bg:#fabd2f fg:#282828"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#427b58"
format = '[[ $symbol $branch ](fg:#ebdbb2 bg:#427b58)]($style)'

[git_status]
style = "bg:#427b58"
format = '[[($all_status$ahead_behind )](fg:#ebdbb2 bg:#427b58)]($style)'

[nodejs]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#8ec07c bg:#282828)]($style)'

[rust]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#d65d0e bg:#282828)]($style)'

[golang]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#83a598 bg:#282828)]($style)'

[php]
symbol = ""
style = "bg:#282828"
format = '[[ $symbol ($version) ](fg:#83a598 bg:#282828)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[  $time ](fg:#ebdbb2 bg:#282828)]($style)'
